### ISSUE TITLE
Does the profile add syntax and/or semantics?

### ISSUE THREAD

**Issue by RubenVerborgh** [pietercolpaert/TREE-profiles#2]
In https://github.com/pietercolpaert/TREE-N3-profiles/issues/1, I wrote about the profile in terms of adding hints/semantics. However, I realized that I don't fully understand this bit yet.

**Is the proposed profile one of syntax, semantics, or both?**

Let me clarify:
- JSON-LD is a semantic extension of JSON; it provides an additional interpretation of existing JSON documents.
- https://www.w3.org/TR/json-ld11-streaming/ is a syntactical profile, in that it constrains itself to a subset of existing JSON-LD syntax. It does not add meaning to existing JSON-LD.

I'm now trying to understand whether TREE-N3-profiles…
1. …is a syntactical profile, so a subset of Turtle (namely the subset of all possible Turtle files that have a specific ordering and use specific comments), with no additional semantic interpretation? That is, it would be a streaming profile, that makes optimizations to the latency when parsing a document. But the semantic contents, beyond timeline differences, of parsing the same document as `text/turtle` or `text/tree+turtle` is identical.
2. …a semantic profile, in that it adds meaning. Namely, it adds a grouping to the resulting interpretation that cannot be derived in other ways. (With "other ways", I mean that the current examples in https://github.com/pietercolpaert/TREE-N3-profiles/blob/main/README.md can also be separated by `_:x tree:member ?s. ?s ?p ?o`.
3. …a combination of the above.

Note that there might be little difference between 2/3 in _this_ case. For an example in which 2/3 are separate, consider graphs in (pretty-printed) TriG versus N-Quads.

**Comment by pietercolpaert** [comment]
It does not add meaning: the grouping is merely a performance upgrade. The member extraction algorithm in TREE defines how one can use CBD, Shape Topologies and named graphs to extract members from a page. It requires the page to be fully read and indexed first though.
